# Generated by Django 5.0 on 2025-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('instructions', models.TextField()),
                ('cuisine_type', models.CharField(blank=True, max_length=80)),
                ('prep_time_min', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('favorite', 'Favorite'), ('to_try', 'To Try'), ('made_before', 'Made Before')], default='to_try', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
